title: "Diego Carboni's homepage"
description: "Bookmark this to keep an eye on my project updates!"
url: "https://carboni123.github.io"
baseurl: ""
github_username: "carboni123"
logo: "/assets/images/site-card.jpg"
twitter:
  username: "carboni_01"
  card: summary_large_image

# Set a default Open Graph / Twitter Card image for every page
defaults:
  - scope:
      path: ""            # applies to all files
    values:
      image: "/assets/images/site-card.jpg"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: pages-themes/slate@v0.2.0
